### ISSUE TITLE
Add WiNS data

### ISSUE THREAD

**Issue by TLouf** [complexity-core/complexity-core.github.io#11]
- [x] upload logo in good resolution / vector format to [`assets/images/organizations_logos`](https://github.com/complexity-core/complexity-core.github.io/tree/main/assets/images/organizations_logos)
- [x] add markdown file with metadata to [`content/english/organizations`](https://github.com/complexity-core/complexity-core.github.io/tree/main/content/english/organizations)

**Comment by elenacandellone** [comment]
I'm still looking for a HQ logo, nobody has it ahah

**Comment by TLouf** [comment]
Worst case I can generate an svg from the png, the logo is simple enough
