### ISSUE TITLE
Add WWCS data

### ISSUE THREAD

**Issue by TLouf** [complexity-core/complexity-core.github.io#12]
- [x] upload logo in good resolution / vector format to [`assets/images/organizations_logos`](https://github.com/complexity-core/complexity-core.github.io/tree/main/assets/images/organizations_logos)
- [x] add markdown file with metadata to [`content/english/organizations`](https://github.com/complexity-core/complexity-core.github.io/tree/main/content/english/organizations)

**Comment by elenacandellone** [comment]
sara might add the logo
