### ISSUE TITLE
Add Complexity Cat data

### ISSUE THREAD

**Issue by TLouf** [complexity-core/complexity-core.github.io#14]
- [x] upload logo in good resolution / vector format to [`assets/images/organizations_logos`](https://github.com/complexity-core/complexity-core.github.io/tree/main/assets/images/organizations_logos)
- [x] add markdown file with metadata to [`content/english/organizations`](https://github.com/complexity-core/complexity-core.github.io/tree/main/content/english/organizations)

(if you want to have Complexity Cat considered as an org, actually creating the issue I had a doubt)

**Comment by amahury** [comment]
Hi there! I just added both the logo and metadata for complexity cat. Thank you so much and you need anything else please met le know!

**Comment by TLouf** [comment]
Thanks :)
